### ISSUE TITLE
US 05.01.01 - Search Function for Open Experiments

### ISSUE THREAD

**Issue by xuanrui-work** [CMPUT301W21T18/PreemptiveOOP#18]
**User Story**
US 05.01.01
As an experimenter, I want to specify a keyword, and search for all experiments that are available.

**Rationale**
- A search function is to be implemented inside the experiments database.
- Any user can provide a series of keywords to search for experiments.

**Story Points = 4/5**
**Risk Level = High**

**Comment by sorafeng** [comment]
Working on this story
