### ISSUE TITLE
US 05.02.01 - UI for Experiment Search Result

### ISSUE THREAD

**Issue by xuanrui-work** [CMPUT301W21T18/PreemptiveOOP#19]
**User Story**
US 05.02.01
As an experimenter, I want search results to show each experiment with its description, owner username, and status.

**Rationale**
- A UI is to be created to show the experiment search result obtained from #18, for example a list.
- Each result displayed in the UI should show an experiment with its description, owner username, and status.

**Story Points = 4/5**
**Risk Level = Low**

**Comment by xuanz215** [comment]
finished
