### ISSUE TITLE
US 04.04.01 Guest Login

### ISSUE THREAD

**Issue by sorafeng** [CMPUT301W21T18/PreemptiveOOP#53]
**User Story**
US 04.04.01
As an owner or experimenter, I do not want to log into my application using a username and password.

**Rationale**
- A user can use the application without login with any username and password.
- A user can use all the function in the application without login.
- A user name need to be determined before accessing to the functions of the application.

**Story Points 2/5**
**Risk Level = Medium**

**Comment by sorafeng** [comment]
Working on this user story

**Comment by sorafeng** [comment]
Assume database assign a new random id to the guest user

**Comment by xuanz215** [comment]
No longer needed
