### ISSUE TITLE
US 04.01.01 - User Profile Management

### ISSUE THREAD

**Issue by xuanrui-work** [CMPUT301W21T18/PreemptiveOOP#6]
**User Story**
US 04.01.01
As an owner or experimenter, I want a profile with a unique username and my contact information.

**Rationale**
- A user profile management system is to be implemented with a front-end UI to allow the user to create/delete an user account.
- The user account is bind to a username and contains the user's contact info.

**Story Points = 5/5**
**Risk Level = Medium**

**Comment by JoshuaKan** [comment]
work on this
