### ISSUE TITLE
US 01.01.01 - Publish a new Experiment 

### ISSUE THREAD

**Issue by xiaolei1998** [CMPUT301W21T18/PreemptiveOOP#9]
**User story**
US 01.01.01
As an owner, I want to publish an experiment with a description, a region, and a minimum number of trials.

**Rationale**

- When a new experiment is created, the experiment needs to have some specific attributes(description, Region, min number of trails), and the user who created the experiment becomes the owner of the experiment.
- The experiment can be selected to be 1 of 4 types: counts, binomial trials, non-negative integer counts, or measurement trials.

**story points  = 5/5 
Risk Level : Medium**

**Comment by sorafeng** [comment]
Working on this story case

**Comment by sorafeng** [comment]
Also implement the display experiment list, create experiment, view experiment detail
